/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author Cristian Gomez
 */
public class V_Main extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(V_Main.class.getName());

    /**
     * Creates new form C_Main
     */
    public V_Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        desktop = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        menuAgregarCategoria = new javax.swing.JMenuItem();
        menuConsultarEditarCategorias = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        menuRegistrarMarca = new javax.swing.JMenuItem();
        menuConsultarEditarMarca = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        menuRegistrarProducto = new javax.swing.JMenuItem();
        menuConsultarEditarProducto = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        menuRegistrarProveedor = new javax.swing.JMenuItem();
        menuConsultarEditarProveedor = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuRegistrarCompra = new javax.swing.JMenuItem();
        menuConsultarCompras = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        menuNuevaVenta = new javax.swing.JMenuItem();
        menuConsultarVentas = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jMenuItem3.setText("jMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        desktop.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/tienda del barrio - logo.png"))); // NOI18N

        desktop.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout desktopLayout = new javax.swing.GroupLayout(desktop);
        desktop.setLayout(desktopLayout);
        desktopLayout.setHorizontalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 794, Short.MAX_VALUE)
        );
        desktopLayout.setVerticalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jMenu4.setText("Catálogos");

        jMenu3.setText("Categorías");

        menuAgregarCategoria.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        menuAgregarCategoria.setText("Agregar categoría");
        jMenu3.add(menuAgregarCategoria);

        menuConsultarEditarCategorias.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, 0));
        menuConsultarEditarCategorias.setText("Consultar / Editar categoría");
        jMenu3.add(menuConsultarEditarCategorias);

        jMenu4.add(jMenu3);

        jMenu6.setText("Marcas");

        menuRegistrarMarca.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        menuRegistrarMarca.setText("Registrar marca");
        jMenu6.add(menuRegistrarMarca);

        menuConsultarEditarMarca.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, 0));
        menuConsultarEditarMarca.setText("Consultar / Editar marca");
        jMenu6.add(menuConsultarEditarMarca);

        jMenu4.add(jMenu6);

        jMenu5.setText("Productos");

        menuRegistrarProducto.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, 0));
        menuRegistrarProducto.setText("Registrar producto");
        jMenu5.add(menuRegistrarProducto);

        menuConsultarEditarProducto.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F6, 0));
        menuConsultarEditarProducto.setText("Consultar / Editar producto");
        jMenu5.add(menuConsultarEditarProducto);

        jMenu4.add(jMenu5);

        jMenu8.setText("Proveedores");

        menuRegistrarProveedor.setText("Registrar proveedor");
        jMenu8.add(menuRegistrarProveedor);

        menuConsultarEditarProveedor.setText("Consultar / Editar proveedor");
        jMenu8.add(menuConsultarEditarProveedor);

        jMenu4.add(jMenu8);

        jMenuBar1.add(jMenu4);

        jMenu7.setText("Inventario");

        jMenuItem4.setText("Consultar existencias");
        jMenu7.add(jMenuItem4);

        jMenuItem5.setText("Ajuste de inventario");
        jMenu7.add(jMenuItem5);

        jMenuBar1.add(jMenu7);

        jMenu2.setText("Compras");

        menuRegistrarCompra.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        menuRegistrarCompra.setText("Registrar compra");
        jMenu2.add(menuRegistrarCompra);

        menuConsultarCompras.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F7, 0));
        menuConsultarCompras.setText("Consultar compras");
        jMenu2.add(menuConsultarCompras);

        jMenuBar1.add(jMenu2);

        jMenu1.setText("Ventas");

        menuNuevaVenta.setText("Registrar venta");
        jMenu1.add(menuNuevaVenta);

        menuConsultarVentas.setText("Consultar ventas");
        jMenu1.add(menuConsultarVentas);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new V_Main().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JDesktopPane desktop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    public javax.swing.JMenuItem menuAgregarCategoria;
    public javax.swing.JMenuItem menuConsultarCompras;
    public javax.swing.JMenuItem menuConsultarEditarCategorias;
    public javax.swing.JMenuItem menuConsultarEditarMarca;
    public javax.swing.JMenuItem menuConsultarEditarProducto;
    public javax.swing.JMenuItem menuConsultarEditarProveedor;
    public javax.swing.JMenuItem menuConsultarVentas;
    public javax.swing.JMenuItem menuNuevaVenta;
    public javax.swing.JMenuItem menuRegistrarCompra;
    public javax.swing.JMenuItem menuRegistrarMarca;
    public javax.swing.JMenuItem menuRegistrarProducto;
    public javax.swing.JMenuItem menuRegistrarProveedor;
    // End of variables declaration//GEN-END:variables
}
